.PHONY: all dependencies install test test-verbose

ROOT_DIR := $(shell dirname $(realpath $(lastword $(MAKEFILE_LIST))))

all: dependencies install test

dependencies:
	go get -t -v ./...
	go build -v ./...
install: generate
	go install -v ./...
test:
	go test -race ./...
test-verbose:
	go test -race -v ./...
